AbsensiPanti-main/routes/web.php
<?php
// use Illuminate\Routing\Route;

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();
// Route::get('qr-code', function () {
//     return  QRCode::text('mey123')
//         ->setOutfile('images/mey123-qr-code.png')
//         ->png();
// });


Route::middleware(['auth'])->group(function () {

    Route::get('/', 'HomeController@cekLogin');

});

Route::get('/login', 'LoginController@showLogin')->middleware('guest')->name('home');

Route::post('/login', 'LoginController@postLogin')->middleware('guest')->name('login');


Route::middleware(['auth.admin'])->prefix('admin')->name('admin.')->group(function () {

    // Admin Dahsboard

    Route::get('dashboard', 'Admin\DashboardController@index')
    ->name('dashboard');

    // User Admin
    Route::prefix('users')->group(function () {

        Route::prefix('admin')->group(function () {
            Route::get('/', 'Admin\UserAdminController@index')
                ->name('usersAdmin');
        });

        // User
        Route::prefix('user')->group(function () {
            Route::get('/', 'Admin\UsersUserController@index')
                ->name('userUser');
            Route::get('/ShowRegisterUser', 'Admin\UsersUserController@create')
                ->name('showRegister');
            Route::post('/Register', 'Admin\UsersUserController@store')
                ->name('register');
            Route::get('/{id}/edit', 'Admin\UsersUserController@edit')
                ->name('showEditUser');
            Route::post('/edit', 'Admin\UsersUserController@update')
                ->name('editUser');
        });
    });

    // Absen
    Route::prefix('absen')->group(function(){
        Route::get('/', 'Admin\AbsenController@index')
        ->name('absen');
        Route::get('/{id}/detail', 'Admin\AbsenController@detailAbsen')
        ->name('absenDetail');
        Route::get('/{id}/ShowAbsen', 'Admin\AbsenController@store')
        ->name('showAbsen');
        Route::post('/tambahAbsen', 'Admin\AbsenController@create')
        ->name('addAbsen');
    });

    Route::prefix('laporan')->group(function () {
        Route::get('/', 'Admin\LaporanController@index')
        ->name('laporan');
        Route::get('/filterAbsen', 'Admin\LaporanController@exportexcel')
        ->name('filterAbsenexport');
        Route::post('/filterAbsen', 'Admin\LaporanController@filterAbsen')
            ->name('filterAbsen');

    });


});

// Auth User
Route::middleware(['auth.user'])->prefix('user')->name('user.')->group(function () {
    Route::get('Dashboard', 'User\DashboardController@index')
    ->name('dashboard');

        Route::prefix('absen')->group(function () {
            Route::get('/', 'User\AbsenController@index')
            ->name('absen');
             Route::post('/absen', 'User\AbsenController@create')
            ->name('absenUser');
        });

        Route::prefix('laporan')->group(function () {
            Route::get('/', 'User\LaporanController@index')
            ->name('laporan');
        });

});




Route::get('/logout', 'LoginController@logout')->middleware('auth')->name('logout');

AbsensiPanti-main/app/Http/Controllers/Admin/LaporanController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Exports\AbsenExport;
use Maatwebsite\Excel\Facades\Excel;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class LaporanController extends Controller
{
    public function index(Request $request)
    {
        $absens = DB::table('users')
        ->select('users.nama as user', 'users.email', 'absens.status_absen_id', 'absens.tanggal', 'status_absens.nama', 'detail_absens.jam_masuk', 'detail_absens.jam_keluar')
        ->join('absens', 'absens.user_id', '=', 'users.id')
        ->join('detail_absens', 'detail_absens.absen_id', '=', 'absens.id')
        ->join('status_absens', 'status_absens.id', '=', 'absens.status_absen_id')
        ->latest()
        ->get();
        // dd($absens);
        $a = 1;

        $this->pageTitle = 'Laporan Absen';

        return view('Admin.Laporan.index', $this->withDashboardData([
            'absens' => $absens,
            'a' => $a,
        ]));
    }

    public function filterAbsen(Request $request)
    {
        $a=1;
        $bulan = $request->get('month');
        $tahun = $request->get('year');

        $absens = DB::table('users')
        ->select('users.nama as user', 'users.email', 'absens.status_absen_id', 'absens.tanggal', 'status_absens.nama', 'detail_absens.jam_masuk', 'detail_absens.jam_keluar')
        ->join('absens', 'absens.user_id', '=', 'users.id')
        ->join('detail_absens', 'detail_absens.absen_id', '=', 'absens.id')
         ->join('status_absens', 'status_absens.id', '=', 'absens.status_absen_id')
         ->whereYear('tanggal', '=', $tahun)
        ->whereMonth('tanggal', '=', $bulan)
        ->latest()
        ->get();
        // dd($absens);
        return view('Admin.Laporan.index', $this->withDashboardData([
            'absens' => $absens,
            'a' => $a,
        ]));

    }

    public function exportexcel()
    {
        return (new AbsenExport)->download('absen.xlsx');
    }
}

AbsensiPanti-main/app/Http/Controllers/User/LaporanController.php
<?php

namespace App\Http\Controllers\User;

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class LaporanController extends Controller
{
    public function index()
    {
        // $absen =  Absen::where('user_id', Auth::id())->get();

        $absens = DB::table('users')
        ->join('absens', 'absens.user_id', '=', 'users.id')
        ->join('detail_absens', 'detail_absens.absen_id', '=', 'absens.id')
        ->where('users.id', Auth::id())
        ->get();

        $i = 1;

        $this->pageTitle = 'Laporan Absen';

        return view('User.Laporan.index', $this->withDashboardData([
            'absens' => $absens,
            'i' => $i,
        ]));
    }

    public function store()
    {
        return view('User.Laporan.indexTambah', $this->withDashboardData([
        ]));
    }
}

AbsensiPanti-main/resources/views/Admin/Laporan/index.blade.php
 @extends('layouts.admin.app')

 @section('content')
 <section class="content ">
     <div class="box">
         <form id="form_daftar" action="{{ route('admin.filterAbsen') }}" method="POST">
             @csrf
             <div class="box-body">
                 <section class="content">
                     <div class="row">
                         <div class="box box-primary">
                             <div class="box-header with-border">
                                 <i class="fa fa-address-card"></i>
                                 <h3 class="box-title">Laporan Absen</h3>
                             </div>
                             <div class="box-body">
                                 <div class="form-group">
                                     <label>Tahun<span style="color: red"> *</span></label>
                                     <select style="cursor:pointer;" class="form-control" id="tag_select" name="year">
                                         <option value="0" selected disabled> Pilih Tahun</option>
                                         <?php
                                                            $year = date('Y');
                                                            $min = $year - 60;
                                                            $max = $year;
                                                            for( $i=$max; $i>=$min; $i-- ) {
                                                            echo '<option value='.$i.'>'.$i.'</option>';
                                                            }?>
                                     </select>
                                 </div>
                                 <div class="form-group">
                                     <label>Bulan<span style="color: red"> *</span></label>
                                     <select style="cursor:pointer;margin-top:1.5em;margin-bottom:1.5em;"
                                         class="form-control" id="tag_select" name="month">
                                         <option value="0" selected disabled> Pilih Bulan</option>
                                         <option value="01"> Januari</option>
                                         <option value="02"> Februari</option>
                                         <option value="03"> Maret</option>
                                         <option value="04"> April</option>
                                         <option value="05"> Mei</option>
                                         <option value="06"> Juni</option>
                                         <option value="07"> Juli</option>
                                         <option value="08"> Agustus</option>
                                         <option value="09"> September</option>
                                         <option value="10"> Oktober</option>
                                         <option value="11"> November</option>
                                         <option value="12"> Desember</option>
                                     </select>
                                 </div>
                                 <div class="box-body">
                                     <button type="submit" class="btn btn-primary pull-right" form="form_daftar">
                                         Submit
                                     </button>
                                 </div>
                             </div>
                         </div>
                     </div>
                 </section>
             </div>
         </form>
     </div>

     <div class="box">
         <div class="box-header with-border">
             <div class="card-body">
                 <h3 class="box-title">Laporan User</h3>
                 <div class="card-body  pull-right">
                     <a href="{{ route('admin.filterAbsenexport') }}">
                         <button type="button" class="btn btn-block btn-danger">Export</button>
                     </a>
                 </div>
             </div>
         </div>
         <div class="box-body">
             <table id="table_admin" class="table table-bordered table-striped dataTable">
                 <thead>
                     <tr>
                         <th>No</th>
                         <th>Nama</th>
                         <th>Email</th>
                         <th>Tanggal</th>
                         <th style="text-align: center;">Kehadiran</th>
                         <th style="text-align: center;">Jam Masuk</th>
                         <th style="text-align: center;">Jam Keluar</th>
                     </tr>
                 </thead>
                 <tbody>
                     @foreach ($absens as $absen)
                     <tr>
                         <td >{{ $a++ }}</td>
                         <td>{{  $absen->user }}</td>
                         <td>{{ $absen->email }}</td>
                         <td>{{ date('l, d F Y', strtotime($absen->tanggal)) }}</td>
                       @if ($absen->status_absen_id == 1)
                                 <td style="text-align: center;"><span class="label label-success">Masuk</span></td>
                        @endif
                        @if ($absen->status_absen_id == 2)
                                <td style="text-align: center;"><span class="label label-danger">Tidak Masuk</span></td>
                        @endif
                        @if ($absen->status_absen_id == 3)
                                <td style="text-align: center;"><span class="label label-warning">Sakit</span></td>
                        @endif
                        @if ($absen->status_absen_id == 4)
                                 <td style="text-align: center;"><span class="label label-primary">Cuti</span></td>
                        @endif

                        @if ($absen->jam_masuk == null )
                            <td style="text-align: center;"> <b> - </b>  </td>
                        @else
                            <td style="text-align: center;">{{ $absen->jam_masuk }}</td>
                        @endif
                        @if ($absen->jam_keluar == null )
                            <td style="text-align: center;"> <b> - </b>  </td>
                        @else
                            <td style="text-align: center;">{{ $absen->jam_keluar }}</td>
                        @endif
                     </tr>
                     @endforeach
                 </tbody>
             </table>
         </div>
     </div>
 </section>
 @endsection
 @push('script')
 <script>
     $(function () {
         $('#table_admin').DataTable()
     })
 </script>
 @endpush