AbsensiPanti-main/routes/web.php
<?php
// use Illuminate\Routing\Route;

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();
// Route::get('qr-code', function () {
//     return  QRCode::text('mey123')
//         ->setOutfile('images/mey123-qr-code.png')
//         ->png();
// });


Route::middleware(['auth'])->group(function () {

    Route::get('/', 'HomeController@cekLogin');

});

Route::get('/login', 'LoginController@showLogin')->middleware('guest')->name('home');

Route::post('/login', 'LoginController@postLogin')->middleware('guest')->name('login');


Route::middleware(['auth.admin'])->prefix('admin')->name('admin.')->group(function () {

    // Admin Dahsboard

    Route::get('dashboard', 'Admin\DashboardController@index')
    ->name('dashboard');

    // User Admin
    Route::prefix('users')->group(function () {

        Route::prefix('admin')->group(function () {
            Route::get('/', 'Admin\UserAdminController@index')
                ->name('usersAdmin');
        });

        // User
        Route::prefix('user')->group(function () {
            Route::get('/', 'Admin\UsersUserController@index')
                ->name('userUser');
            Route::get('/ShowRegisterUser', 'Admin\UsersUserController@create')
                ->name('showRegister');
            Route::post('/Register', 'Admin\UsersUserController@store')
                ->name('register');
            Route::get('/{id}/edit', 'Admin\UsersUserController@edit')
                ->name('showEditUser');
            Route::post('/edit', 'Admin\UsersUserController@update')
                ->name('editUser');
        });
    });

    // Absen
    Route::prefix('absen')->group(function(){
        Route::get('/', 'Admin\AbsenController@index')
        ->name('absen');
        Route::get('/{id}/detail', 'Admin\AbsenController@detailAbsen')
        ->name('absenDetail');
        Route::get('/{id}/ShowAbsen', 'Admin\AbsenController@store')
        ->name('showAbsen');
        Route::post('/tambahAbsen', 'Admin\AbsenController@create')
        ->name('addAbsen');
    });

    Route::prefix('laporan')->group(function () {
        Route::get('/', 'Admin\LaporanController@index')
        ->name('laporan');
        Route::get('/filterAbsen', 'Admin\LaporanController@exportexcel')
        ->name('filterAbsenexport');
        Route::post('/filterAbsen', 'Admin\LaporanController@filterAbsen')
            ->name('filterAbsen');

    });


});

// Auth User
Route::middleware(['auth.user'])->prefix('user')->name('user.')->group(function () {
    Route::get('Dashboard', 'User\DashboardController@index')
    ->name('dashboard');

        Route::prefix('absen')->group(function () {
            Route::get('/', 'User\AbsenController@index')
            ->name('absen');
             Route::post('/absen', 'User\AbsenController@create')
            ->name('absenUser');
        });

        Route::prefix('laporan')->group(function () {
            Route::get('/', 'User\LaporanController@index')
            ->name('laporan');
        });

});




Route::get('/logout', 'LoginController@logout')->middleware('auth')->name('logout');

AbsensiPanti-main/app/Models/Absen.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class Absen extends Model
{
    public $table = 'absens';

    public $primarykey = 'id';

    const CREATED_AT = 'create_time';
    const UPDATED_AT = 'update_time';
    public $timestamps = false;

    public function setUpdatedAt($value)
    {
        return $this;
    }

    protected $fillable = [
        'id', 'user_id', 'status_absen_id', 'tanggal',
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function detailabsen()
    {
        return $this->belongsTo(DetailAbsen::class);
    }

    // public static function getAbsen()
    // {
    //     $absens = DB::table('users')
    //     ->join('absens', 'absens.user_id', '=', 'users.id')
    //     ->join('detail_absens', 'detail_absens.absen_id', '=', 'absens.id')
    //     ->latest()
    //     ->get()->toArray();

    //     return $absens;
    // }

}

AbsensiPanti-main/app/Http/Controllers/Admin/AbsenController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Absen;
use App\Models\DetailAbsen;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class AbsenController extends Controller
{
    public function index()
    {
        $user = User::where('role_id', 2)->get();
        // dd($user);
        $i = 1;
        $this->pageTitle = 'Absen';

        return view('Admin.Absen.home', $this->withDashboardData([
            'dataUser' => $user,
            'i' => $i
        ]));
    }

    public function detailAbsen(Request $request)
    {
        // dd($request->id);
        $user = User::where('id', $request->id )->first();
        // dd($user->id);
        $i = 1;
        $absens = DB::table('users')
        ->join('absens', 'absens.user_id', '=', 'users.id')
        ->join('detail_absens', 'detail_absens.absen_id', '=', 'absens.id')
        ->where('users.id', $request->id)
        ->get();
        // dd($absens);

        $this->pageTitle = 'Laporan Absen';

        return view('Admin.Absen.detail', $this->withDashboardData([
            'absens' => $absens,
            'i' => $i,
            'user' =>$user,
        ]));

    }

    public function store(Request $request)
    {
        // dd($request->id);
        $user = User::where('id', $request->id)->first();
        // dd($request->id);
        $absens = DB::table('users')
        ->join('absens', 'absens.user_id', '=', 'users.id')
        ->join('detail_absens', 'detail_absens.absen_id', '=', 'absens.id')
        ->where('users.id', $request->id)
        ->get();
        // ->first();
        // dd($absens);
        return view('Admin.Absen.showAbsen', $this->withDashboardData([
            'absens' => $absens,
            'user' => $user,
        ]));

    }

    public function create(Request $request)
    {
        $absenn = Absen::create([
            'user_id' => $request->user,
            'status_absen_id' => $request->status,
            'tanggal' => $request->tanggal,
        ]);

        $detailabsen = DetailAbsen::create([
            'user_id' => $request->user,
            'absen_id' => $absenn->id,
        ]);
        // dd($detailabsen);
        session()->flash('success', 'Update Successfully');
        return redirect()->route('admin.absen');
    }
}

AbsensiPanti-main/app/Http/Controllers/User/AbsenController.php
<?php

namespace App\Http\Controllers\User;

use App\Models\Absen;
use App\Models\DetailAbsen;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class AbsenController extends Controller
{
    public function index(){

        $user = User::where('id', Auth::id())->first();

        $this->pageTitle = "Absen";

        return view('User.Absen.absenUser', $this->withDashboardData([
            'user' => $user,
            ]));
    }

    public function create(Request $request)
    {
        $user = User::where('kode', $request->kode)->first();
        $Loginuser = User::where('id', Auth::id())->first();
        // dd($Loginuser->kode);
        $tanggal = date("Y-m-d H:i:s");
        $jam  = date("G:i:s");

        $absen = Absen::whereDate('tanggal', date('Y-m-d'))->where('user_id', Auth::id())->get()->first();
        $absencek = Absen::where('user_id', Auth::id())->whereDate('tanggal', date('Y-m-d'))->get()->first();
        $detailabsen = DetailAbsen::where('user_id', Auth::id())->get()->first();

        if($user->kode == $Loginuser->kode) {
            if (empty($absen)) {
                if ($user) {
                    $absenn = Absen::create([
                        'user_id' => $request->id,
                        'status_absen_id' => 1,
                        'tanggal' => $tanggal,
                    ]);
                    $detailabsen = DetailAbsen::create([
                        'user_id' => $request->id,
                        'absen_id' => $absenn->id,
                        'jam_masuk' => $jam,
                    ]);
                    session()->flash('success', 'Karyawan berhasil melakukan Absen Masuk!');
                }
            }
            if ($detailabsen->jam_keluar == null && $absencek) {
                DetailAbsen::where('absen_id', $detailabsen->absen_id)->update(['jam_keluar' => $jam]);
                session()->flash('success', 'Karyawan berhasil melakukan Absen Keluar!');
            }
            session()->flash('warning', 'Absen Hanya Satu Kali Sehari !');
        }else{
            session()->flash('warning', 'tidak sama');
        }

        return redirect()->route('user.dashboard');
    }
}

AbsensiPanti-main/resources/views/Admin/Absen/detail.blade.php
 @extends('layouts.admin.app')

@section('content')
<section class="content ">
    <div class="box">
        <div class="box-header with-border">
            <div class="card-body">
                <h3 class="box-title">Data Laporan Absen</h3>
                <div class="card-body  pull-right">
                    <a href="{{ route('admin.showAbsen', ['id' => $user->id]) }}">
                        <button type="button" class="btn btn-block btn-primary">Tambah</button>
                    </a>

                </div>
            </div>
        </div>
        <div class="box-body">
            <table id="table_admin" class="table table-bordered table-striped dataTable">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Nama</th>
                        <th>Tnggal</th>
                        <th>Absen</th>
                        <th>Jam Masuk</th>
                        <th>Jam Keluar</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($absens as $absen)
                    <tr>
                        <td>{{ $i++ }}</td>
                        <td>{{ $absen->nama}}</td>
                        <td>{{ $absen->tanggal }}</td>
                         @if ($absen->status_absen_id == 1)
                                 <td ><span class="label label-success">Masuk</span></td>
                        @endif
                        @if ($absen->status_absen_id == 2)
                                <td ><span class="label label-danger">Tidak Masuk</span></td>
                        @endif
                        @if ($absen->status_absen_id == 3)
                                <td ><span class="label label-warning">Sakit</span></td>
                        @endif
                        @if ($absen->status_absen_id == 4)
                                 <td><span class="label label-primary">Cuti</span></td>
                        @endif
                         @if ($absen->jam_masuk == null )
                            <td style="text-align: center;"> <b> - </b>  </td>
                        @else
                            <td style="text-align: center;">{{ $absen->jam_masuk }}</td>
                        @endif
                        @if ($absen->jam_keluar == null )
                            <td style="text-align: center;"> <b> - </b>  </td>
                        @else
                            <td style="text-align: center;">{{ $absen->jam_keluar }}</td>
                        @endif
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</section>
@endsection
@push('script')
<script src="{{ asset('/adminlte/bower_components/datatables.net/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('/adminlte/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>

<script>
    $(function () {
        $('#table_admin').DataTable()
    })
</script>
@endpush

AbsensiPanti-main/resources/views/Admin/Absen/home.blade.php
 @extends('layouts.admin.app')

 @section('content')
 <section class="content ">
     <div class="box">
         <div class="box-header with-border">
             <div class="card-body">
                 <h3 class="box-title">Data Absen</h3>
             </div>
         </div>
         <div class="box-body">
             <table id="table_admin" class="table table-bordered table-striped dataTable">
                 <thead>
                     <tr>
                         <th>Id</th>
                         <th>Nama</th>
                         <th>Kode</th>
                         <th>Email</th>
                         <th>Alamat</th>
                         <th>Phone</th>
                         <th>Qrcode</th>
                         <th style="width: 50px;">Action</th>
                     </tr>
                 </thead>
                 <tbody>
                     @foreach ($dataUser as $user)
                     <tr>
                         <td>{{ $i++ }}</td>
                         <td>{{ $user->nama }}</td>
                         <td>{{ $user->kode }}</td>
                         <td>{{ $user->email }}</td>
                         <td>{{ $user->alamat }}</td>
                         <td>{{ $user->telphon }}</td>
                         <td><img width="100px" src="{{ url($user->qrcode ?? '') }}" alt="User picture"></td>
                         <div class="btn-group">
                             <td class="text-center"><a href="{{ route('admin.absenDetail', ['id' => $user->id]) }}"
                                     class="btn"><i class="fa fa-eye"></i></a>
                             </td>
                         </div>
                     </tr>
                     @endforeach
                 </tbody>
             </table>
         </div>
     </div>
 </section>
 @endsection
 @push('script')
 <script>
     $(function () {
         $('#table_admin').DataTable()
     })
 </script>
 @endpush

AbsensiPanti-main/resources/views/Admin/Absen/showAbsen.blade.php
@extends('layouts.admin.app')

@section('content')
<section class="content ">
    <div class="box">
        <form id="form_daftar" action="{{ route('admin.addAbsen') }}" method="POST">
            @csrf
            <div class="box-body">
                <section class="content">
                    <div class="row">
                        <div class="box box-primary">
                            <div class="box-header with-border">
                                <i class="fa fa-address-card"></i>
                                <h3 class="box-title">Absen User</h3>
                            </div>
                            <div class="box-body">
                                <div class="form-group">
                                    <label>Kehadiran</label>
                                    <select name="status" class="form-control">
                                        <option value="1">Hadir</option>
                                        <option value="2">Tidak Hadir</option>
                                        <option value="3">Sakit</option>
                                        <option value="4">Cuti</option>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label>Tanggal<span style="color: red"> *</span></label>
                                    <input name="tanggal" type="date" class="form-control" placeholder=""
                                        value="" required>
                                </div>
                                <div class="form-group">
                                    <input name="user" type="hidden" class="form-control" placeholder=""
                                        value="{{ $user->id }}" required>
                                </div>
                                <div class="box-body">
                                    <button type="submit" class="btn btn-primary pull-right" form="form_daftar">
                                        Submit
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </form>
    </div>
</section>
@endsection
@push('script')
<script src="{{ asset('/adminlte/bower_components/datatables.net/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('/adminlte/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>

<script>
    $(function () {
        $('#table_admin').DataTable()
    })
</script>
@endpush