AbsensiPanti-main/routes/web.php
<?php
// use Illuminate\Routing\Route;

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();
// Route::get('qr-code', function () {
//     return  QRCode::text('mey123')
//         ->setOutfile('images/mey123-qr-code.png')
//         ->png();
// });


Route::middleware(['auth'])->group(function () {

    Route::get('/', 'HomeController@cekLogin');

});

Route::get('/login', 'LoginController@showLogin')->middleware('guest')->name('home');

Route::post('/login', 'LoginController@postLogin')->middleware('guest')->name('login');


Route::middleware(['auth.admin'])->prefix('admin')->name('admin.')->group(function () {

    // Admin Dahsboard

    Route::get('dashboard', 'Admin\DashboardController@index')
    ->name('dashboard');

    // User Admin
    Route::prefix('users')->group(function () {

        Route::prefix('admin')->group(function () {
            Route::get('/', 'Admin\UserAdminController@index')
                ->name('usersAdmin');
        });

        // User
        Route::prefix('user')->group(function () {
            Route::get('/', 'Admin\UsersUserController@index')
                ->name('userUser');
            Route::get('/ShowRegisterUser', 'Admin\UsersUserController@create')
                ->name('showRegister');
            Route::post('/Register', 'Admin\UsersUserController@store')
                ->name('register');
            Route::get('/{id}/edit', 'Admin\UsersUserController@edit')
                ->name('showEditUser');
            Route::post('/edit', 'Admin\UsersUserController@update')
                ->name('editUser');
        });
    });

    // Absen
    Route::prefix('absen')->group(function(){
        Route::get('/', 'Admin\AbsenController@index')
        ->name('absen');
        Route::get('/{id}/detail', 'Admin\AbsenController@detailAbsen')
        ->name('absenDetail');
        Route::get('/{id}/ShowAbsen', 'Admin\AbsenController@store')
        ->name('showAbsen');
        Route::post('/tambahAbsen', 'Admin\AbsenController@create')
        ->name('addAbsen');
    });

    Route::prefix('laporan')->group(function () {
        Route::get('/', 'Admin\LaporanController@index')
        ->name('laporan');
        Route::get('/filterAbsen', 'Admin\LaporanController@exportexcel')
        ->name('filterAbsenexport');
        Route::post('/filterAbsen', 'Admin\LaporanController@filterAbsen')
            ->name('filterAbsen');

    });


});

// Auth User
Route::middleware(['auth.user'])->prefix('user')->name('user.')->group(function () {
    Route::get('Dashboard', 'User\DashboardController@index')
    ->name('dashboard');

        Route::prefix('absen')->group(function () {
            Route::get('/', 'User\AbsenController@index')
            ->name('absen');
             Route::post('/absen', 'User\AbsenController@create')
            ->name('absenUser');
        });

        Route::prefix('laporan')->group(function () {
            Route::get('/', 'User\LaporanController@index')
            ->name('laporan');
        });

});




Route::get('/logout', 'LoginController@logout')->middleware('auth')->name('logout');

AbsensiPanti-main/resources/views/layouts/admin/app.blade.php
@extends('layouts.master')

@section('users')
    @include('layouts.admin.navbar')

    @include('layouts.admin.sidebar')

    <div class="content-wrapper">
        @yield('content')
    </div>
@endsection

AbsensiPanti-main/resources/views/layouts/admin/navbar.blade.php
@extends('components.navbar')

@push('info')
    <p>
        {{ str_limit(App\Models\User::where('id', Auth::id())->first()->nama, 32, '...') }}
        <small>Admin</small>
    </p>
@endpush

AbsensiPanti-main/resources/views/layouts/admin/sidebar.blade.php
@extends('components.sidebar')

@section('sidebar')

<li class="header">ADMIN NAVIGATION</li>
{{-- Side Bar DashBoard --}}
<li class="{{ Request::is('admin/dashboard') ? 'active' : '' }}">
    <a href="{{ route('admin.dashboard') }}">
        <i class="fa fa-dashboard"></i>
        <span>Dashboard</span>
    </a>
</li>

{{-- Side Bar Users --}}
<li class="treeview {{ Request::is('admin/users/*') ? 'active' : ''}}">
    <a href="#">
        <i class="fa fa-users"></i>
        <span>Users</span>
        <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
        </span>
    </a>
    <ul class="treeview-menu">
        <li class="{{ Request::is('admin/users/admin') || Request::is('admin/users/admin/*') ? 'active' : ''}}">
            <a href="{{ route('admin.usersAdmin') }}"><i class="fa fa-circle-o"></i> Admin</a>
        </li>
        <li class="{{ Request::is('admin/users/user') || Request::is('admin/users/user/*') ? 'active' : ''}}">
            <a href="{{ route('admin.userUser') }}"><i class="fa fa-circle-o"></i> User</a>
        </li>
    </ul>
</li>

{{-- Side Bar Absen --}}
<li class="{{ Request::is('admin/absen') ? 'active' : '' }}">
    <a href="{{ route('admin.absen') }}">
        <i class="fa fa-address-card"></i>
        <span>Absen</span>
    </a>
</li>

<li class="{{ Request::is('admin/laporan') ? 'active' : '' }}">
    <a href="{{ route('admin.laporan') }}">
    <i class="fa fa-file"></i>
        <span>Laporan</span>
    </a>
</li>
@endsection